apiVersion: v1
kind: Pod
metadata:
  labels:
    environment: kube-env1
    schedule: businesshours
    service: test-service
  name: test-deployment
  namespace: kube-env1
spec:
  containers:
  - env:
    - name: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          key: vault-token
          name: dvault-token
    image: test-docker-image
    imagePullPolicy: Always
    name: test-deployment
    resources:
      limits:
        cpu: "1"
        memory: 1280Mi
      requests:
        cpu: 250m
        memory: 512Mi
