apiVersion: v1
kind: Service
metadata:
  labels:
    environment: kube-env1
  name: test-service
  namespace: kube-env1
spec:
  ports:
  - name: https
    port: 80
    protocol: TCP
    targetPort: 443
  selector:
    deployment: test-deployment
  sessionAffinity: None
  type: ClustsdferIP
